- connect to T4 GPU
- create data folder and drag-drop inside
- create plots folder
- drag drop rest of files

In [1]:
!pip install -r requirements.txt

# NOTE Limitations of Part1 due to Decode method
- decode method (tests our trained model) is hardcoded (and cannot modify as grader will likely have that implementation for decode)so assumes:
  - using cpu
  - no batching
- therefore a more optimal approach would've been to:
  - train and inference on gpu (faster training and inferencing) bc would allow use of larger transformer (larger d_model embedding dim and larger feedforward dim d_internal)
    - on cpu, default transformer paper params: d_model=512, d_internal(dim_feedforward)=2048 ends up taking about 3 mins per epoch (not efficient)
  - batching
    - im able to batch for my training but note my inferencing (on dev (test) dataset) does not use batching (and decode method does not either) so output log_probs was handled differently for my loss function than for training bc in forward I had to remove batch dim if batchsize=1 -> since decode method argmax axis=1 assumes no batch dimension

# Part 1
- if --task BEFOREAFTER, in code comment positional encoding operation in Transformer forward
- if --task BEFORE use positional encoding

In [ ]:
!python letter_counting.py --task BEFOREAFTER

Namespace(task='BEFOREAFTER', train='data/lettercounting-train.txt', dev='data/lettercounting-dev.txt', output_bundle_path='classifier-output.json')
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ']
10000 lines read in
1000 lines read in
Epoch 0 loss 225.520373
Epoch 1 loss 67.804799
Epoch 2 loss 17.145683
Epoch 3 loss 6.210209
Epoch 4 loss 3.075545
Epoch 5 loss 1.740892
Epoch 6 loss 6.657256
Epoch 7 loss 0.877065
Epoch 8 loss 0.701277
Epoch 9 loss 0.563867
Dev loss 2.114813
INPUT 0: heir average albedo 
GOLD 0: array([0, 2, 0, 1, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 2])
PRED 0: array([0, 2, 0, 1, 2, 2, 0, 2, 1, 2, 0, 2, 2, 2, 0, 0, 2, 0, 0, 2])
INPUT 1: ed by rank and file 
GOLD 1: array([1, 1, 2, 0, 0, 2, 0, 1, 1, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 2])
PRED 1: array([1, 1, 2, 0, 0, 2, 0, 1, 1, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 2])
INPUT 2: s can also extend in
GOLD 2: array([1, 2, 0, 1, 2, 2, 1, 0, 1

In [2]:
!python letter_counting.py --task BEFORE

Namespace(task='BEFORE', train='data/lettercounting-train.txt', dev='data/lettercounting-dev.txt', output_bundle_path='classifier-output.json')
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ']
10000 lines read in
1000 lines read in
Epoch 0 loss 215.220104
Epoch 1 loss 117.297072
Epoch 2 loss 44.137706
Epoch 3 loss 19.995091
Epoch 4 loss 12.224274
Epoch 5 loss 8.147050
Epoch 6 loss 5.890897
Epoch 7 loss 4.034489
Epoch 8 loss 3.350244
Epoch 9 loss 2.986180
Dev loss 14.087654
INPUT 0: heir average albedo 
GOLD 0: array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 2, 1, 2, 0, 0, 2, 0, 0, 2])
PRED 0: array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 2, 1, 2, 0, 0, 2, 0, 0, 2])
INPUT 1: ed by rank and file 
GOLD 1: array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 2])
PRED 1: array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 2])
INPUT 2: s can also extend in
GOLD 2: array([0, 0, 0, 0, 0, 1, 1, 0, 1,

In [ ]:
import numpy as np
arr=[
    np.array([1,2,3]),
    np.array([4,5,6]),
    np.array([7,8,9]),
    np.array([11,4,1])
]
print(np.argmax(arr, axis=1))

arr=[
    np.array([1,2,3]),
    np.array([4,5,6]),
    np.array([7,8,9]),
    np.array([11,4,1])
]
arr=[arr] # in decode method, it assumes no batch dimension, if there is one, the argmax is incorrect (wrong axis)
print(np.argmax(arr, axis=1))

[2 2 2 0]
[[3 2 2]]


# Part 2

In [3]:
!python lm.py --model NEURAL

Namespace(model='NEURAL', train_path='data/text8-100k.txt', dev_path='data/text8-dev.txt', output_bundle_path='output.json')
100000 chars read in
500 chars read in
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ']
First 100 characters of train:
 anarchism originated as a term of abuse first used against early working class radicals including t
Starting epoch 0 - lr=1.000000e-04
Epoch 0 training avg loss (nats/token): 2.715817, perplexity: 15.1170
Epoch 0 dev   avg loss (nats/token): 2.392445, perplexity: 10.9402
Starting epoch 1 - lr=1.000000e-04
Epoch 1 training avg loss (nats/token): 2.431421, perplexity: 11.3750
Epoch 1 dev   avg loss (nats/token): 2.323557, perplexity: 10.2119
Starting epoch 2 - lr=1.000000e-04
Epoch 2 training avg loss (nats/token): 2.368586, perplexity: 10.6823
Epoch 2 dev   avg loss (nats/token): 2.263342, perplexity: 9.6152
Starting epoch 3 - lr=1.000000e-04
Epoch 3 training a

In [ ]:
ex = ""
if ex == "":
  print("true")

true


# Chunking and Creating dataset

In [ ]:
from typing import List
import random
def text_to_indices(text: str, vocab_index) -> List[int]:
    """Convert string to list of token indices using vocab_index.index_of(c)."""
    return [vocab_index[c] for c in text]

def chunk_non_overlapping(indices: List[int], seq_len: int,
                          drop_last: bool = True,
                          random_offset: bool = False) -> List[List[int]]:
    """
    Partition indices into non-overlapping chunks of length seq_len.
    If random_offset is True pick a start in [0, seq_len-1] each call (useful per-epoch).
    If drop_last is False, the final short chunk is left-padded (requires pad_idx provided externally).
    Returns list of chunks (each length <= seq_len). If you want guaranteed length seq_len,
    either drop_last=True or post-pad/pad-left externally.
    """
    if random_offset:
        start = random.randint(0, seq_len - 1)
    else:
        start = 0
    chunks = []
    for i in range(start, len(indices), seq_len):
        chunk = indices[i:i+seq_len]
        if len(chunk) < seq_len and drop_last:
            break
        chunks.append(chunk)
    return chunks
import numpy as np
chunks = chunk_non_overlapping(np.arange(20), 3)
print(chunks)
chunks2 = chunk_non_overlapping(np.arange(20), 6, random_offset=True)
print(chunks2)

vocab_index = {"a": 0, "b": 1, "c": 2, "d": 3}
text = "abcd"
print(text_to_indices(text, vocab_index))

for _ in range(4):
  random.shuffle(chunks)
  print(chunks)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11]), array([12, 13, 14]), array([15, 16, 17])]
[array([ 5,  6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15, 16])]
[0, 1, 2, 3]
[array([3, 4, 5]), array([ 9, 10, 11]), array([0, 1, 2]), array([12, 13, 14]), array([6, 7, 8]), array([15, 16, 17])]
[array([6, 7, 8]), array([3, 4, 5]), array([15, 16, 17]), array([12, 13, 14]), array([0, 1, 2]), array([ 9, 10, 11])]
[array([ 9, 10, 11]), array([15, 16, 17]), array([12, 13, 14]), array([6, 7, 8]), array([3, 4, 5]), array([0, 1, 2])]
[array([15, 16, 17]), array([0, 1, 2]), array([ 9, 10, 11]), array([12, 13, 14]), array([6, 7, 8]), array([3, 4, 5])]


In [ ]:
# batching
import torch
batch_size = 4
i=0
print(chunks)
for b in range(0, len(chunks), batch_size):
  batch_chunks = chunks[b:b+batch_size]
  batch_tensor = torch.tensor(np.array(batch_chunks), dtype=torch.long) # (batch_size, seq_len)
  print(f"Batch {i}")
  print(batch_tensor)
  i+=1

[array([15, 16, 17]), array([0, 1, 2]), array([ 9, 10, 11]), array([12, 13, 14]), array([6, 7, 8]), array([3, 4, 5])]
Batch 0
tensor([[15, 16, 17],
        [ 0,  1,  2],
        [ 9, 10, 11],
        [12, 13, 14]])
Batch 1
tensor([[6, 7, 8],
        [3, 4, 5]])


In [ ]:
# output of model with loss
arr = np.array([
    [[0.1, 0.2, 0.3],
    [0.4, 0.5, 0.6],
    [0.7, 0.8, 0.9]],

    [[1.1, 1.2, 1.3],
     [1.4, 1.5, 1.6],
     [1.7, 1.8, 1.9]]
    ])
logits = torch.tensor(arr, dtype=torch.float)
print(logits.shape) # (2,3,3) -> (batch_size, seq_len, vocab_size)
print(logits)
# logits = logits.reshape(-1, logits.shape[-1])
# targets = batch_tensor.reshape(-1)
logits = logits.view(-1, logits.shape[-1])
targets = batch_tensor.view(-1)
print("\nReshape For loss")
print(logits.shape)
print(targets.shape)
print(logits)
print(targets)

torch.Size([2, 3, 3])
tensor([[[0.1000, 0.2000, 0.3000],
         [0.4000, 0.5000, 0.6000],
         [0.7000, 0.8000, 0.9000]],

        [[1.1000, 1.2000, 1.3000],
         [1.4000, 1.5000, 1.6000],
         [1.7000, 1.8000, 1.9000]]])

Reshape For loss
torch.Size([6, 3])
torch.Size([6])
tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000],
        [1.1000, 1.2000, 1.3000],
        [1.4000, 1.5000, 1.6000],
        [1.7000, 1.8000, 1.9000]])
tensor([6, 7, 8, 3, 4, 5])


# Model Forward

In [ ]:
indices = torch.tensor([1,2,3,4])
if len(indices.shape) == 1:
  indices = indices.unsqueeze(0)
print(indices)
print(indices.shape)

tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


In [ ]:
indices = torch.tensor([1,2,3,4]).unsqueeze(0)
seq_len = 2
if indices.shape[1] > seq_len:
    indices = indices[:, -seq_len:] # (batch_size, seq_len)
print(indices)
print(indices.shape)

tensor([[3, 4]])
torch.Size([1, 2])


In [ ]:
indices = torch.tensor([3,4]).unsqueeze(0)
seq_len = 6
emb = torch.nn.Embedding(5, 3, padding_idx=0)
# RIGHT ALIGNED PADDING
if indices.shape[1] < seq_len:
    # pad with PAD token index at the beginning if sequence is shorter than seq_len
    pad_length = seq_len - indices.shape[1]
    pad_idx = emb.padding_idx
    pad_tensor = torch.full((indices.shape[0], pad_length), pad_idx, dtype=torch.long, device=indices.device) # (batch_size, pad_length)
    indices = torch.cat([pad_tensor, indices], dim=1)
print(indices)
print(indices.shape)

tensor([[0, 0, 0, 0, 3, 4]])
torch.Size([1, 6])


In [ ]:
print(indices, "\nAfter roll:")
indices = torch.roll(indices, shifts=1, dims=1)
print(indices)

tensor([[0, 0, 0, 0, 3, 4]]) 
After roll:
tensor([[4, 0, 0, 0, 0, 3]])


In [ ]:
space_idx = 2
indices[:, 0] = space_idx
print(indices)
x=emb(indices)
print(x)

tensor([[2, 0, 0, 0, 0, 3]])
tensor([[[ 0.6382, -0.6015,  0.7876],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.6401, -0.1063,  0.2540]]], grad_fn=<EmbeddingBackward0>)


In [ ]:
batched=True
input_size = x.shape[-2]
pos_emb = torch.nn.Embedding(input_size, 3)
indices_to_embed = torch.tensor(np.asarray(range(0, input_size))).type(torch.LongTensor)
if batched:
    # Use unsqueeze to form a [1, seq len, embedding dim] tensor -- broadcasting will ensure that this
    # gets added correctly across the batch
    print(indices_to_embed)
    emb_unsq = pos_emb(indices_to_embed).unsqueeze(0)
print(emb_unsq)
print("\nSum\n", x+emb_unsq)

x_one_more_sample = torch.cat((x, emb_unsq), dim=0)
print(x_one_more_sample.shape)
print(x_one_more_sample)

print("\nSum\n:", x_one_more_sample+emb_unsq)


tensor([0, 1, 2, 3, 4, 5])
tensor([[[ 0.4769,  1.3433,  0.3484],
         [-2.1324,  1.0726, -0.6919],
         [-0.3836, -0.6994,  1.3595],
         [ 2.0871,  0.1587,  0.5033],
         [-0.0736, -0.6491, -0.2882],
         [-0.3321, -0.0394,  0.5740]]], grad_fn=<UnsqueezeBackward0>)

Sum
 tensor([[[ 1.1151,  0.7418,  1.1360],
         [-2.1324,  1.0726, -0.6919],
         [-0.3836, -0.6994,  1.3595],
         [ 2.0871,  0.1587,  0.5033],
         [-0.0736, -0.6491, -0.2882],
         [ 0.3079, -0.1457,  0.8281]]], grad_fn=<AddBackward0>)
torch.Size([2, 6, 3])
tensor([[[ 0.6382, -0.6015,  0.7876],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.6401, -0.1063,  0.2540]],

        [[ 0.4769,  1.3433,  0.3484],
         [-2.1324,  1.0726, -0.6919],
         [-0.3836, -0.6994,  1.3595],
         [ 2.0871,  0.1587,  0.5033],
         [-0.0736, -0.6491, -0.2882],
         [-

In [ ]:
test_emb = torch.nn.Embedding(5, 3)
with torch.no_grad():
  test_emb.weight[3].zero_()
print(test_emb.weight)

Parameter containing:
tensor([[ 0.8021,  0.8342,  0.4761],
        [ 0.4370,  0.2659, -0.9019],
        [ 0.3983, -0.9058,  0.0152],
        [ 0.0000,  0.0000,  0.0000],
        [-0.4759,  0.0561,  0.5250]], requires_grad=True)


# get_next_char_log_probs and get_log_prob_sequence tests

In [ ]:
import torch
import numpy as np
def index_of(char):
  vocab = {chr(i): i - ord('a') for i in range(ord('a'), ord('z') + 1)}
  vocab[' '] = 26
  vocab['#'] = 27
  return vocab[char]

def get_next_char_log_probs(context):
  # make sure here to be in eval mode and detach from gpu (place back onto cpu) and convert to numpy array
  context_indices = [index_of(c) for c in context]
  context_tensor = torch.tensor(context_indices, dtype=torch.long) # (seq_len,)
  print("getnextchar\nContext: ", context)
  print("Context tensor: ", context_tensor, "\n")

  logits = torch.arange(5*28, dtype=torch.float).view(1, 5, 28) # (1, seq_len, vocab_size)
  print("Logits shape: ", logits.shape)
  print("Logits: ", logits)
  last_logits = logits[0, -1, :] # (vocab_size,)
  print("Last logits: ", last_logits)
  log_probs = torch.log_softmax(last_logits, dim=0) # (vocab_size,)
  print("Log probs: ", log_probs)
  return log_probs.numpy()

def get_log_prob_sequence(next_chars, context):
  total_log_prob = 0.0
  cur_context = context
  # if next_chars is a string,
  for c in next_chars:
      print("Current c: ", c)
      print("Current context: ", cur_context)
      logp = get_next_char_log_probs(cur_context)  # numpy array of log-probs
      char_idx = index_of(c)
      print("Char idx: ", char_idx)
      print("logp[char_idx]: ", logp[char_idx])
      total_log_prob += float(logp[char_idx])
      cur_context = cur_context + c
  return total_log_prob


contexts = [" ", " a person ", " some person "]
next_seqs = ["s", "sits", "stands"]
sane = True
for context in contexts:
    for next_seq in next_seqs:
        print("\n\nContext: ", context)
        print("Next seq: ", next_seq)
        log_prob = get_log_prob_sequence(next_seq, context)
        print("Log prob SUM: ", log_prob)
        # if log_prob > 0.0:
        #     sane = False
        #     print("ERROR: sanity checks failed, LM log probability %f is invalid" % (log_prob))
        # log_prob_from_single_probs = 0.0
        # for i in range(0, len(next_seq)):
        #     # print(repr(context + next_seq[0:i]))
        #     # print(repr(next_seq[i]))
        #     next_char_log_probs = lm.get_next_char_log_probs(context + next_seq[0:i]) # gets prob of next char given context + previous chars
        #     # print(repr(next_char_log_probs))
        #     log_prob_from_single_probs += next_char_log_probs[vocab_index.index_of(next_seq[i])] # acquire prob of ground truth char and sum
        # if abs(log_prob_from_single_probs - log_prob) > 1e-3:
        #     # if difference between result of get_log_prob_sequence and summing get_next_char_log_probs is too large,
        #     # then implementation of either or of the methods are wrong (results may have some variance but should be < 1e-3 difference)
        #     sane = False
        #     print("ERROR: sanity checks failed, LM prob from sequence and single characters disagree: %f %f" % (log_prob, log_prob_from_single_probs))



Context:   
Next seq:  s
Current c:  s
Current context:   
getnextchar
Context:   
Context tensor:  tensor([26]) 

Logits shape:  torch.Size([1, 5, 28])
Logits:  tensor([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
           11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
           22.,  23.,  24.,  25.,  26.,  27.],
         [ 28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,
           39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,
           50.,  51.,  52.,  53.,  54.,  55.],
         [ 56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
           67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
           78.,  79.,  80.,  81.,  82.,  83.],
         [ 84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,
           95.,  96.,  97.,  98.,  99., 100., 101., 102., 103., 104., 105.,
          106., 107., 108., 109., 110., 111.],
         [112., 113., 114., 115., 116., 

In [ ]:
vocab = {chr(i): i - ord('a') for i in range(ord('a'), ord('z') + 1)}
print(vocab)

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


# sliding chunks

In [ ]:
from typing import List
import numpy as np

def sliding_window_chunks(indices: List[int], seq_len: int, stride: int = 1, drop_short: bool = True) -> List[List[int]]:
    """
    Create overlapping chunks using a sliding window.
    - stride < seq_len will create overlapping windows.
    - drop_short: if True drop the final partial window, otherwise include it as a shorter chunk.
    Returns a list of chunks (each of length seq_len, except possibly the final one when drop_short=False).
    """
    if len(indices) < seq_len:
        return [] if drop_short else [indices]
    chunks = [indices[i:i+seq_len] for i in range(0, len(indices) - seq_len + 1, stride)]
    if not drop_short:
        # include any trailing short tail
        tail_start = (len(indices) - seq_len + 1) + ((len(indices) - seq_len) % stride)
        tail = indices[tail_start + seq_len:]
        if tail:
            chunks.append(tail)
    return chunks


seq_len = 6
stride = max(1, seq_len // 2)
train_chunks = sliding_window_chunks(np.arange(20), seq_len=seq_len, stride=stride, drop_short=True)
print(np.shape(train_chunks))
print(train_chunks)

seq_len = 6
stride = seq_len
train_chunks = sliding_window_chunks(np.arange(20), seq_len=seq_len, stride=stride, drop_short=True)
print(np.shape(train_chunks))
print(train_chunks)

seq_len = 6
stride = 1
train_chunks = sliding_window_chunks(np.arange(20), seq_len=seq_len, stride=stride, drop_short=True)
print(np.shape(train_chunks))
print(train_chunks)

(5, 6)
[array([0, 1, 2, 3, 4, 5]), array([3, 4, 5, 6, 7, 8]), array([ 6,  7,  8,  9, 10, 11]), array([ 9, 10, 11, 12, 13, 14]), array([12, 13, 14, 15, 16, 17])]
(3, 6)
[array([0, 1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10, 11]), array([12, 13, 14, 15, 16, 17])]
(15, 6)
[array([0, 1, 2, 3, 4, 5]), array([1, 2, 3, 4, 5, 6]), array([2, 3, 4, 5, 6, 7]), array([3, 4, 5, 6, 7, 8]), array([4, 5, 6, 7, 8, 9]), array([ 5,  6,  7,  8,  9, 10]), array([ 6,  7,  8,  9, 10, 11]), array([ 7,  8,  9, 10, 11, 12]), array([ 8,  9, 10, 11, 12, 13]), array([ 9, 10, 11, 12, 13, 14]), array([10, 11, 12, 13, 14, 15]), array([11, 12, 13, 14, 15, 16]), array([12, 13, 14, 15, 16, 17]), array([13, 14, 15, 16, 17, 18]), array([14, 15, 16, 17, 18, 19])]
